# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 16:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.TextField(default='')),
                ('artist', models.TextField(default='')),
                ('rank', models.IntegerField(default=101)),
                ('week', models.DateField(default=datetime.date(1980, 1, 1))),
            ],
        ),
    ]
