# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tune_throwback', '0002_auto_20160324_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SongRank',
        ),
    ]
