# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tune_throwback', '0003_delete_songrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='spotify_id',
            field=models.TextField(default=''),
        ),
    ]
